### ISSUE TITLE
Usage sample how to use this library.

### ISSUE THREAD

**Issue by yassinelmalyh** [Pmovil/swagger-codenameone-codegen#1]
Hello,

i'm trying to use swagger codegen with codename.
is there any usage sample how to use this library.

Thanks in advance.
Cordially

**Comment by FabricioCabeca** [comment]
Hi there ! 

This library is meant to be used as an additional module for Swagger Codegen. For instructions about how to download, compile, and generate additional modules:

https://github.com/swagger-api/swagger-codegen.git 

Once you do so you will be able for instance to generate a codenameone REST client library for [XKCD](https://github.com/APIs-guru/openapi-directory/tree/master/APIs/xkcd.com) with something like this:

`java -DdebugOperations -jar swagger-codegen/modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -l Codenameone -i xkcd.com/1.0.0/swagger.yaml -o XkcdClient`

Please be aware that it was made using rather old versions from both Swagger Codegen and Codename One.
